Review my project
Danieldotcomcoder/Reviewmycodeproject pull request #1
Opened 2021-09-19 10:17 UTC by Danieldotcomcoder

2021-09-19 10:52 UTC, Danieldotcomcoder commented on index.html
> +  <section id="main">
I think it would be better to use "class" attributes instread of "id".

2021-09-19 10:54 UTC, Danieldotcomcoder commented on index.html
> +  <section id="main">
I think it would be better to use "class" attributes instead of "id".

2021-09-19 10:55 UTC, Danieldotcomcoder commented on index.html
> +
Please try not to leave spaces.

2021-09-19 11:00 UTC, Danieldotcomcoder commented on index.html
> +  <script src="js/index.js"></script>
I would suggest not to link javascript file if you dont need one.

2021-09-20 07:51 UTC, Danieldotcomcoder commented
I would suggest to add information to your readme file to explain your project more.

2021-09-20 08:24 UTC, Davidosky007 requested changes
Hi @Danieldotcomcoder 👋 , 

Good job so far! 💪 
* Nice job using inline comments to review ✔️ 
* Great work using polite comments ✔️ 
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
* Kindly explain or give reasons why a change was requested this would help the student learn and know why the change is important 👍 
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- You can include emojis and gifs to make your code review more human-friendly 👽.


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2021-09-20 08:24 UTC, Davidosky007 commented on index.html
> +
* Kindly explain why you requested a change - it might be obvious to you but not to someone else 👍.

2021-09-20 08:24 UTC, Davidosky007 commented on index.html
> +  <section id="main">
* Kindly explain why you requested a change - state why using `class` instead of `id` is better 👍.

2021-09-20 08:24 UTC, Davidosky007 commented on index.html
> +  <script src="js/index.js"></script>
* Kindly explain why you requested a change - it might be obvious to you but not to someone else 👍.

2021-09-20 08:57 UTC, Danieldotcomcoder commented on index.html
> +  <section id="main">
I think it would be better to use "class" attributes instead of "id" 👍. Because classes can be used for multiples HTML elements 
which can be very helpful while ID's are unique and must only be used for one HTML element . Check this link for more information 😃 : https://www.codecademy.com/articles/classes-vs-ids

2021-09-20 09:02 UTC, Danieldotcomcoder commented on index.html
> +
Please try not to leave spaces. This will make your code look cleaner 👍.

2021-09-20 09:08 UTC, Danieldotcomcoder commented
Hello ,

- You did a very good job with your code 👍.

But there still some issues that need to be fixed.😉

Required Changes ♻️:

_Check the comments under the review._

2021-09-20 09:21 UTC, oxenprogrammer approved these changes
Hi @Danieldotcomcoder , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-20 09:25 UTC, merged